"""
winrate_identifier.py
=====================
STEP 4 of 4

Reads signals_parsed.py (auto-generated by parse_results.py).
Writes winrate_report.txt and prints to screen simultaneously.
"""

import sys
import os
from datetime import datetime, timezone

OUTPUT_FILE = 'winrate_report.txt'
INPUT_FILE  = 'signals_parsed.py'

# ── load signals from parse_results output ────────────────────
if not os.path.exists(INPUT_FILE):
    print(f'ERROR: {INPUT_FILE} not found.')
    print('Run parse_results.py first.')
    sys.exit(1)

exec(open(INPUT_FILE).read())   # loads SIGNALS list into scope

# ── Tee: write to screen + file simultaneously ────────────────
class Tee:
    def __init__(self, filepath):
        self.terminal = sys.stdout
        self.file     = open(filepath, 'w', encoding='utf-8')
    def write(self, msg):
        self.terminal.write(msg)
        self.file.write(msg)
    def flush(self):
        self.terminal.flush()
        self.file.flush()
    def close(self):
        self.file.close()

# ── helpers ───────────────────────────────────────────────────
TP = 6.0
SL = 2.0

def wr(sigs):
    w = sum(1 for s in sigs if s[7] == 'WIN')
    l = sum(1 for s in sigs if s[7] == 'LOSS')
    c = w + l
    return (w/c*100, w, l, c) if c > 0 else (0.0, 0, 0, 0)

def tag(r, c):
    if c < 3:               return '⚠  few trades'
    if r >= 60:             return '✅ strong edge'
    if r >= 50:             return '✅ edge'
    if r >= 40:             return '〰 marginal'
    return                         '❌ no edge'

# ── main analysis ─────────────────────────────────────────────
def analyse(signals):
    gen = datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    W   = 65

    def div(char='='):
        print(char * W)

    def p(line=''):
        print(line)

    div('=')
    p('WIN RATE IDENTIFIER — BACKTEST SIGNAL ANALYSIS')
    p(f'Generated : {gen}')
    p(f'Signals   : {len(signals)} total')
    p(f'Source    : {INPUT_FILE}')
    div('=')

    # overall
    rate, w, l, c = wr(signals)
    ongoing = sum(1 for s in signals if s[7] == 'ONGOING')
    pnl     = (w * TP) - (l * SL)
    p()
    p('OVERALL')
    div('-')
    p(f'  Win rate  : {rate:.1f}%  (W:{w}  L:{l}  /  {c} closed)')
    p(f'  Ongoing   : {ongoing}  (excluded from win rate)')
    p(f'  Total PnL : {pnl:+.2f}%  (TP={TP}%  SL={SL}%  equal-size)')
    div('-')

    # by distance zone
    p()
    p('BY DISTANCE ZONE')
    div('-')
    zone_a = [s for s in signals if 0.20 <= s[2] <= 0.35]
    zone_b = [s for s in signals if 0.50 <= s[2] <= 0.65]
    zone_m = [s for s in signals if 0.35 <  s[2] <  0.50]
    for label, grp in [
        ('Zone A  0.20–0.35%  close bounce', zone_a),
        ('Zone B  0.50–0.65%  far bounce',   zone_b),
        ('Middle  0.35–0.50%  rejected band',zone_m),
    ]:
        r, w2, l2, c2 = wr(grp)
        p(f'  {label:<36}  {r:>5.1f}%  W:{w2} L:{l2} ({c2})  {tag(r,c2)}')
    div('-')

    # by slope
    p()
    p('BY SLOPE MAGNITUDE  (slope_8bar %)')
    div('-')
    for lo, hi, label in [
        (-999,  -0.30, 'steep     <  -0.30%'),
        (-0.30, -0.20, 'moderate  -0.30 to -0.20%'),
        (-0.20, -0.10, 'mild      -0.20 to -0.10%'),
        (-0.10,  0.00, 'minimal   -0.10 to  0.00%'),
    ]:
        grp = [s for s in signals if lo <= s[3] < hi]
        r, w2, l2, c2 = wr(grp)
        p(f'  {label:<30}  {r:>5.1f}%  W:{w2} L:{l2} ({c2})  {tag(r,c2)}')
    div('-')

    # by ma_accel
    p()
    p('BY MA ACCELERATION  (ma_accel)')
    div('-')
    for lo, hi, label in [
        (-999,   -0.010, 'strong   < -0.010'),
        (-0.010, -0.005, 'moderate -0.010 to -0.005'),
        (-0.005, -0.001, 'mild     -0.005 to -0.001'),
        (-0.001,  0.000, 'weak     -0.001 to  0'),
    ]:
        grp = [s for s in signals if lo <= s[4] < hi]
        r, w2, l2, c2 = wr(grp)
        p(f'  {label:<30}  {r:>5.1f}%  W:{w2} L:{l2} ({c2})  {tag(r,c2)}')
    div('-')

    # by ATR
    p()
    p('BY ATR  (atr_14_pct %)')
    div('-')
    for lo, hi, label in [
        (0.00, 0.20, '0.00–0.20%  very low'),
        (0.20, 0.35, '0.20–0.35%  low'),
        (0.35, 0.45, '0.35–0.45%  medium'),
        (0.45, 0.60, '0.45–0.60%  high'),
        (0.60, 999,  '>= 0.60%   very high'),
    ]:
        grp = [s for s in signals if lo <= s[6] < hi]
        r, w2, l2, c2 = wr(grp)
        p(f'  ATR {label:<28}  {r:>5.1f}%  W:{w2} L:{l2} ({c2})  {tag(r,c2)}')
    div('-')

    # by H4
    p()
    p('BY H4 DIRECTION')
    div('-')
    for h4 in ['FALLING', 'RISING', 'N/A']:
        grp = [s for s in signals if s[5] == h4]
        r, w2, l2, c2 = wr(grp)
        note = '  ← target condition' if h4 == 'FALLING' else \
               '  ← F8 should block these' if h4 == 'RISING' else ''
        p(f'  H4={h4:<8}  {r:>5.1f}%  W:{w2} L:{l2} ({c2}){note}')
    div('-')

    # by symbol
    p()
    p('BY SYMBOL')
    div('-')
    p(f'  {"Symbol":<16} {"WR%":>5}  {"W":>3} {"L":>3} {"C":>4} {"Total":>5}  Bar')
    div('-')
    syms = sorted(set(s[0] for s in signals))
    rows = []
    for sym in syms:
        grp = [s for s in signals if s[0] == sym]
        r, w2, l2, c2 = wr(grp)
        rows.append((sym, r, w2, l2, c2, len(grp)))
    rows.sort(key=lambda x: x[1], reverse=True)
    for sym, r, w2, l2, c2, total in rows:
        bar = '█' * int(r / 10)
        p(f'  {sym:<16} {r:>5.1f}  {w2:>3} {l2:>3} {c2:>4} {total:>5}  {bar}  {tag(r,c2)}')
    div('-')

    # recommendations
    p()
    p('RECOMMENDATIONS')
    div('-')

    ra, _, _, ca = wr(zone_a)
    rb, _, _, cb = wr(zone_b)
    if   ca >= 3 and ra > rb + 10: p(f'  ZONES   Zone A ({ra:.1f}%) >> Zone B ({rb:.1f}%) — consider Zone A only')
    elif cb >= 3 and rb > ra + 10: p(f'  ZONES   Zone B ({rb:.1f}%) >> Zone A ({ra:.1f}%) — consider Zone B only')
    else:                           p(f'  ZONES   A ({ra:.1f}%) and B ({rb:.1f}%) comparable — keep both')

    best_atr = max(
        [(lo, hi, lbl) for lo, hi, lbl in [
            (0.00,0.20,'0.00-0.20'),(0.20,0.35,'0.20-0.35'),
            (0.35,0.45,'0.35-0.45'),(0.45,0.60,'0.45-0.60')
        ] if wr([s for s in signals if lo<=s[6]<hi])[3] >= 3],
        key=lambda x: wr([s for s in signals if x[0]<=s[6]<x[1]])[0],
        default=None
    )
    if best_atr:
        p(f'  ATR     Best band: {best_atr[2]}% — consider tightening ATR_MAX_PCT')

    good = [sym for sym, r, w2, l2, c2, _ in rows if r >= 60 and c2 >= 3]
    bad  = [sym for sym, r, w2, l2, c2, _ in rows if r <  35 and c2 >= 3]
    if good: p(f'  KEEP    High-WR symbols: {", ".join(good)}')
    if bad:  p(f'  REMOVE  Low-WR symbols : {", ".join(bad)}')

    best_slope = max(
        [(-999,-0.30,'steep'),(-0.30,-0.20,'moderate'),(-0.20,-0.10,'mild')],
        key=lambda x: wr([s for s in signals if x[0]<=s[3]<x[1]])[0]
    )
    p(f'  SLOPE   Best band: {best_slope[2]}')

    div('=')
    p(f'Saved to: {OUTPUT_FILE}')
    p()


if __name__ == '__main__':
    tee = Tee(OUTPUT_FILE)
    sys.stdout = tee
    try:
        analyse(SIGNALS)
    finally:
        sys.stdout = tee.terminal
        tee.close()
        print(f'\n✅ Written to {OUTPUT_FILE}')
